# Generated by Django 3.1.3 on 2021-05-09 03:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent', models.ForeignKey(on_delete=models.SET('deleted_user'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
